import type { AstrologyLocale } from "../astrology/workspace-copy";

const errors: Record<string, [string, string]> = {
  demo_calculation_unavailable: ["No prepared result for these details or this date. The record can be saved. Demo transits and calendars cover September 2026 in London at 12:00; use a prepared chart or restore those values.", "Для этих данных или даты нет подготовленного результата. Запись можно сохранить. Транзиты и календари демо подготовлены для Лондона на сентябрь 2026, 12:00; открой готовую карту или верни эти значения."],
  demo_unavailable: ["The demo set could not be loaded. Reload to retry; existing records are retained.", "Демонстрационный набор не загрузился. Обнови страницу для повтора; существующие записи сохранены."],
  storage_server_disabled: ["The shared local archive is not enabled on this server. Start the canonical local workspace.", "Общий локальный архив не включён на этом сервере. Запусти основную локальную версию программы."],
  storage_busy: ["Another window is saving the shared archive. Wait for it to finish, then retry.", "Другое окно сохраняет общий архив. Дождись завершения и повтори действие."],
  storage_encryption_unavailable: ["Windows could not protect the local archive. Existing records were not replaced.", "Windows не удалось защитить локальный архив. Существующие записи не заменены."],
  storage_unsafe_path: ["The archive path could not be used safely. The existing files were not changed.", "Не удалось безопасно открыть папку архива. Существующие файлы не изменены."],
  storage_recovery_unavailable: ["This storage does not support shared archive recovery.", "В этом хранилище недоступно восстановление общего архива."],
  storage_recovery_limit: ["Eight recovery entries are already retained. No entry was deleted; the retained work needs review before further recovery.", "Сохранены восемь записей восстановления. Ничего не удалено; перед следующим восстановлением требуется разобрать сохранённую работу."],
  shared_recovery_missing: ["This recovery entry is not available in this browser tab.", "Эта запись восстановления недоступна в данной вкладке браузера."],
  invalid_archive: ["The archive data did not pass validation. Existing records were not replaced.", "Данные архива не прошли проверку. Существующие записи не заменены."],
  invalid_note: ["Enter note text of up to 8,000 characters.", "Введи текст заметки длиной до 8000 символов."],
  note_missing: ["This note is not available for the selected person.", "Эта заметка недоступна у выбранного человека."],
  note_changed: ["The note changed. Reopen it before saving or deleting.", "Заметка изменилась. Открой её заново перед сохранением или удалением."],
  save_note_first: ["Save the note or discard its changes first.", "Сначала сохрани заметку или отмени её изменения."],
  deletion_confirmation_required: ["Open Delete and review the person and related records first.", "Сначала нажми «Удалить» и проверь человека и связанные записи."],
  deletion_changed: ["The data changed after confirmation was opened. Cancel and review the deletion again.", "Данные изменились после открытия подтверждения. Отмени его и проверь удаление заново."],
  invalid_transit_year: ["Choose a year from 1900 to 2100, an IANA time zone and a node mode.", "Укажи год с 1900 по 2100, часовой пояс IANA и режим узлов."],
  invalid_day_panchanga: ["The daily result could not be accepted. The previous saved result is retained.", "Не удалось принять результат дня. Прежний сохранённый результат остаётся."],
  invalid_transit_events: ["The event timeline could not be accepted. The previous result is retained.", "Не удалось принять ленту событий. Прежний результат сохранён."],
  event_time_unavailable: ["This event time cannot be represented in the transit input without losing its leap second.", "Время этого события нельзя перенести в форму транзита без потери високосной секунды."],
  invalid_transit: ["Enter the transit date, time and location.", "Укажи дату, время и место транзитной карты."],
  invalid_transit_result: ["The transit result could not be accepted. Your saved chart is unchanged.", "Не удалось принять транзитный результат. Сохранённая карта не изменена."],
  invalid_month: ["Choose a calendar month between 1900 and 2100.", "Выбери месяц с 1900 по 2100 год."],
  invalid_month_calendar: ["Check the month and location. The calendar could not be accepted.", "Проверь месяц и место. Не удалось принять расчёт календаря."],
  save_result_first: ["Save the current results before opening another person.", "Сохрани текущие результаты перед открытием другого человека."],
  operation_busy: ["An operation is in progress. Wait for it to finish.", "Операция уже выполняется. Дождись её завершения."],
  invalid_profile: ["Enter a name and valid birth details.", "Укажи имя и корректные данные рождения."],
  invalid_date: ["Enter a valid date from 1900 to 2100.", "Укажи корректную дату с 1900 по 2100 год."],
  invalid_time: ["Enter local time as HH:mm or HH:mm:ss.", "Укажи местное время в формате ЧЧ:ММ или ЧЧ:ММ:СС."],
  invalid_timezone: ["Enter a valid IANA time zone.", "Укажи корректный часовой пояс IANA."],
  invalid_latitude: ["Latitude must be between -89 and 89.", "Широта должна быть от −89 до 89."],
  invalid_longitude: ["Longitude must be between -180 and 180.", "Долгота должна быть от −180 до 180."],
  invalid_utcOffsetMinutes: ["Check the UTC offset in minutes.", "Проверь смещение UTC в минутах."],
  invalid_offset: ["The offset does not match this date and time zone.", "Смещение не соответствует дате и часовому поясу."],
  missing_birth_details: ["Astrology needs time, place, coordinates and time zone.", "Для астрологии нужны время, место, координаты и часовой пояс."],
  uncertain_time: ["A precise chart needs an exact birth time; uncertainty analysis is not implemented yet.", "Для точной карты нужно точное время рождения; анализ погрешности пока не реализован."],
  nonexistent_time: ["This civil time does not exist. Check the date and clock change.", "Такого местного времени нет. Проверь дату и перевод часов."],
  ambiguous_time: ["This time occurs twice. Enter the confirmed UTC offset in minutes.", "Это время встречается дважды. Укажи подтверждённое смещение UTC в минутах."],
  profile_missing: ["Create or select a person first.", "Сначала создай или выбери человека."],
  save_draft_first: ["Save the profile before switching people or calculating.", "Сохрани профиль перед сменой человека или расчётом."],
  folder_missing: ["This folder no longer exists.", "Этой папки больше нет."],
  invalid_folder: ["Enter a folder name of up to 120 characters.", "Укажи название папки до 120 символов."],
  folder_exists: ["A folder with this name already exists.", "Папка с таким названием уже существует."],
  calculation_missing: ["Calculate or open a result first.", "Сначала выполни или открой расчёт."],
  select_profile_first: ["Select the person who owns this result.", "Выбери человека, которому принадлежит расчёт."],
  calculation_changed: ["The selected profile changed while calculating. Calculate again.", "Профиль изменился во время расчёта. Выполни расчёт заново."],
  calculation_timeout: ["The calculation timed out. Try again.", "Время ожидания расчёта истекло. Попробуй ещё раз."],
  engine_unavailable: ["The local engine is unavailable. Check the local setup.", "Локальный движок недоступен. Проверь локальный запуск."],
  invalid_calculation: ["The result has an unsupported or invalid structure.", "Структура результата некорректна или не поддерживается."],
  invalid_backup: ["Stored data is invalid or uses an unsupported version. It has not been replaced.", "Сохранённые данные некорректны или имеют неподдерживаемую версию. Они не заменены."],
  storage_unavailable: ["Local storage is unavailable. Recent edits are not saved. Keep this page open and retry storage.", "Локальное хранилище недоступно. Последние изменения не сохранены. Оставь страницу открытой и повтори сохранение."],
  storage_quota: ["Local storage has reached its capacity limit. Recent edits are not saved. Keep this page open while resolving storage space.", "Достигнут лимит локального хранилища. Последние изменения не сохранены. Оставь страницу открытой, пока решаешь вопрос со свободным местом."],
  storage_conflict: ["Another window or browser changed this archive. Automatic overwrite is disabled. Keep this page open until you have preserved any unsaved edits.", "Другое окно или браузер изменили архив. Автоматическая перезапись отключена. Не закрывай страницу, пока не сохранишь незавершённую работу."],
  storage_invalid: ["Stored data could not be validated. It has not been replaced or erased.", "Сохранённые данные не прошли проверку. Они не заменены и не удалены."],
  storage_blocked: ["Another tab is blocking storage. Close the other workspace tab and retry.", "Другая вкладка блокирует хранилище. Закрой другую вкладку кабинета и повтори."],
  workspace_limit: ["This local workspace has reached its record limit.", "Достигнут лимит записей локального кабинета."],
  operation_failed: ["The action could not be completed. Your saved data has not been erased.", "Не удалось выполнить действие. Сохранённые данные не удалены."],
  recovery_missing: ["No original version 1 document is available in this browser.", "В этом браузере нет исходного документа версии 1."],
  legacy_yogini_unavailable: ["This version 1 snapshot has no Yogini. Make an explicit new calculation.", "В снимке версии 1 нет Йогини. Выполни новый расчёт явно."],
  varga_unavailable: ["This snapshot does not contain that divisional chart. Make a new calculation.", "В этом снимке нет выбранной дробной карты. Выполни новый расчёт."],
  invalid_saturn_range: ["Choose a first and last year between 1900 and 2100, in order, and a valid IANA time zone.", "Укажи первый и последний год по порядку в пределах 1900–2100 и корректный часовой пояс IANA."],
  invalid_saturn_timeline: ["The Saturn timeline could not be validated. The previous result is preserved.", "Лента Сатурна не прошла проверку. Прежний результат сохранён."],
  invalid_action: ["The action or its arguments are invalid.", "Действие или его параметры некорректны."]
};
export function workspaceError(code: string, locale: AstrologyLocale) { return (errors[code] ?? errors.operation_failed)[locale === "ru" ? 1 : 0]; }
